### ISSUE TITLE
xylookup math domain error

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/qc#5]
```
15:51:54 obisqc.polling INFO     3 datasets need processing
15:51:54 obisqc       INFO     Started: 1d468f1f-c2b7-4012-8d5b-8e903c200b76
15:51:56 obisqc       INFO     Fetched 10000 rows in 0.60 seconds (10000 of 11250)
15:51:57 obisqc.plugins.datechecker INFO     Processed 10000 rows in 0.66 seconds
15:51:57 obisqc.plugins.taxonomychecker INFO     Processed 10000 rows in 0.07 seconds
Traceback (most recent call last):
  File "/Users/pieter/Desktop/qc/main_obisqc.py", line 18, in <module>
    OBISQC()
  File "/Users/pieter/Desktop/qc/obisqc/__init__.py", line 22, in __init__
    self.polling.start(dataset_id)
  File "/Users/pieter/Desktop/qc/obisqc/polling.py", line 48, in start
    self.callback(res[0][0])
  File "/Users/pieter/Desktop/qc/obisqc/__init__.py", line 26, in process
    self.do_qc(id)
  File "/Users/pieter/Desktop/qc/obisqc/__init__.py", line 93, in do_qc
    results_location = LocationChecker().check(rows)
  File "/Users/pieter/Desktop/qc/obisqc/plugins/locationchecker/__init__.py", line 119, in check
    rows = self.do_xylookup(rows)
  File "/Users/pieter/Desktop/qc/obisqc/plugins/locationchecker/__init__.py", line 85, in do_xylookup
    xys = pyxylookup.lookup(points, shoredistance=True, grids=True, areas=True)
  File "build/bdist.macosx-10.13-x86_64/egg/pyxylookup/__init__.py", line 81, in lookup
    
  File "build/bdist.macosx-10.13-x86_64/egg/pyxylookup/__init__.py", line 37, in _lookup
    
Exception: {"title": "Error looking up data for provided points", "description": "math domain error"}
```

**Comment by pieterprovoost** [comment]
http://api.iobis.org/xylookup?x=-82.4184&y=27.79318

**Comment by pieterprovoost** [comment]
```
Jan 29 17:32:41 obisqc systemd[1]: Started Gunicorn instance to serve the xylookup application.
Jan 29 17:35:14 obisqc gunicorn[26812]: Traceback (most recent call last):
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/lookup.py", line 110, in lookup
Jan 29 17:35:14 obisqc gunicorn[26812]:     shoredists = shoredistance.get_shoredistance(cur, points, pointstable)
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/shoredistance.py", line 138, in get_shoredistance
Jan 29 17:35:14 obisqc gunicorn[26812]:     distances[i*chunksize:((i+1)*chunksize)] = _getcoastlinedistance(chunk, _tree, _coastpoints, _coastlines)
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/shoredistance.py", line 104, in _getcoastlinedistance
Jan 29 17:35:14 obisqc gunicorn[26812]:     d2 = _gc_distancetoline(p, coastpoints[point_index], coastpoints[point_index + 1])
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/shoredistance.py", line 80, in _gc_distancetoline
Jan 29 17:35:14 obisqc gunicorn[26812]:     return _gc_distance(p, pointOnLine)
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/shoredistance.py", line 70, in _gc_distance
Jan 29 17:35:14 obisqc gunicorn[26812]:     return math.acos(math.sin(lat1)*math.sin(lat2) + math.cos(lat1)*math.cos(lat2) * math.cos(dLon))
Jan 29 17:35:14 obisqc gunicorn[26812]: ValueError: math domain error
Jan 29 17:35:14 obisqc gunicorn[26812]: Traceback (most recent call last):
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/lookup.py", line 110, in lookup
Jan 29 17:35:14 obisqc gunicorn[26812]:     shoredists = shoredistance.get_shoredistance(cur, points, pointstable)
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/shoredistance.py", line 138, in get_shoredistance
Jan 29 17:35:14 obisqc gunicorn[26812]:     distances[i*chunksize:((i+1)*chunksize)] = _getcoastlinedistance(chunk, _tree, _coastpoints, _coastlines)
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/shoredistance.py", line 104, in _getcoastlinedistance
Jan 29 17:35:14 obisqc gunicorn[26812]:     d2 = _gc_distancetoline(p, coastpoints[point_index], coastpoints[point_index + 1])
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/shoredistance.py", line 80, in _gc_distancetoline
Jan 29 17:35:14 obisqc gunicorn[26812]:     return _gc_distance(p, pointOnLine)
Jan 29 17:35:14 obisqc gunicorn[26812]:   File "/data/xylookup/git/service/shoredistance.py", line 70, in _gc_distance
Jan 29 17:35:14 obisqc gunicorn[26812]:     return math.acos(math.sin(lat1)*math.sin(lat2) + math.cos(lat1)*math.cos(lat2) * math.cos(dLon))
Jan 29 17:35:14 obisqc gunicorn[26812]: ValueError: math domain error
```

**Comment by pieterprovoost** [comment]
Fixed https://github.com/iobis/xylookup/commit/cf4dfde522372ec4787f40a221a3df5d6bfa422d
